// Package docs Code generated by swaggo/swag. DO NOT EDIT.
//
// This file is committed as a minimal PLACEHOLDER, not the real generated
// spec: `swag init` needs the Go toolchain to parse every @Summary/@Param
// annotation already written throughout internal/delivery/http/v1, and
// that toolchain was not available in the environment this codebase was
// written in (see README.md "Known limitations"). Run:
//
//	make swagger
//	# equivalent to: swag init -g cmd/api/main.go -o docs
//
// once, locally, with Go installed — it OVERWRITES this file with the full
// spec. Until then, /swagger/index.html loads and renders correctly, but
// shows this stub's empty path list, not the full API surface.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "ReplyPilot API",
	Description:      "AI-powered Instagram DM Sales Agent. Placeholder spec — run `make swagger` to generate the full one from handler annotations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
